name: globalstay-etl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scikit-learn>=1.1.0
  - scipy>=1.9.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - ipykernel>=6.0.0
  - pip
  - pip:
    - apache-airflow==2.7.3
    - apache-airflow-providers-microsoft-azure>=6.0.0
    - azure-storage-blob>=12.0.0
    - pyspark>=3.4.0
    - mlflow>=2.7.0
    - pandera>=0.17.0
    - great-expectations>=0.17.0
    - pydantic>=2.0.0
    - retrying>=1.3.4
    - joblib>=1.2.0